### ISSUE TITLE
How to load the datasets from a SQL Database

### ISSUE THREAD

**Issue by bonbonio** [zcreativelabs/react-simple-maps#123]
Hello,

I love this project, and its saved me several days work and a great deal of expense, but I wish to customise the data associated with countries and cities and ideally use data from my database to augment them; to that end, is there an approach to storing the paths in a database, and then providing my own city name, slug, city_id etc from my database in the json needed;

i.e would be better to consume the json via my API, but unsure which data needs retained from the json file to work - I don't need the other data about populations etc then.

**Comment by Unionindesign** [comment]
Hi @bonbonio - I'm not sure exactly what your question is here...but I've been using react-simple-maps since mid-December for a work project, and I've definitely had some hurdles getting data from my company's SQL reporting (PostgreSQL really) into the map! We use navicat to run our queries, but I'm sure any number of desktop applications will let you run a query and export results, I went for exporting as csv so it would be easier to read if anyone needed to look at raw data. I used papaparse to convert the csv to json, and then passed the data through a fairly large function to format the data to suit my needs. I'm not clear if that is what are you trying to do...my biggest hurdle was with map markers, which very specifically want an array called 'coordinates' : [lat, long]. In case you bump into the same hurdles with formatting data, my advise would be (depending on your use case)...if you are getting data in some other format, most of the methods to convert data into json for rendering put quotes around _everything!_ so start with raw, comma delineated data, use parseInt() where necessary, and if you get long/lat coords, use parseFloat() to preserve the decimals, and then .push() into a new array called coordinates. Would be happy to send some code snippets if helpful - but let us know more what you are trying to do!
