### ISSUE TITLE
Zoom controls break after pinch zoom

### ISSUE THREAD

**Issue by rjgux** [zcreativelabs/react-simple-maps#163]
If you pinch/pan to zoom first, the Zoom control buttons no longer work.

Get the following error - `error: <g> attribute transform: Expected number, "translate(NaN NaN)`

This can be seen in the ['Zoom Controls' CodeSandbox](https://codesandbox.io/s/zoom-controls-iwo3f?from-embed), which is on the Zoomable Group docs page - https://www.react-simple-maps.io/docs/zoomable-group/

**Comment by azerio** [comment]
This is because 'handleZoomEnd' on your sandbox breaks as it tries to reference 'zoom' from the event argument passed to it, when in reality zoom is actually found in the second argument of the function.

It should work if you just replace handleZoomEnd with this:

`  function handleZoomEnd(event, position) {
    setZoom(position.zoom);
  }`

**Comment by rjgux** [comment]
> This is because 'handleZoomEnd' on your sandbox breaks as it tries to reference 'zoom' from the event argument passed to it, when in reality zoom is actually found in the second argument of the function.
> 
> It should work if you just replace handleZoomEnd with this:
> 
> ` function handleZoomEnd(event, position) { setZoom(position.zoom); }`

Thank you! This has fixed my issue.
