### ISSUE TITLE
Click trigger map re-renders

### ISSUE THREAD

**Issue by j8seangel** [zcreativelabs/react-simple-maps#21]
Clicking in any place of my app the map triggers a re-render when `disableOptimization` is true.
Any idea why is it happening? 

Also, passing a function to get the geographies styles from the parent doesn't load the styles in the first render correctly and only when a new re-render is triggered (as for example clicking outside) they are updated.

**Comment by zimrick** [comment]
Thanks for spotting this. Just ran a quick test. There was a global `mouseup` event listener assigned to counter a panning bug that occurs when the mouse leaves the map while pressed.

The rerender issue should be fixed in version 0.8.3 (697a42cbb6a7f9870964e835897d2aae4cffe6a4).

Re the issue with the styles, could you post some code so I can better understand what you are trying to do?

**Comment by j8seangel** [comment]
Cool cool cool, thanks! I'll update the version and will let you know how it works.

And related to the other bug I have a parent component what has this function:
```js
computedStyles = geography => {
    const { countriesIncluded } = this.props;
    // array of countries included
    const isCountryIncluded = countriesIncluded.includes(geography.id); 

    if (isCountryIncluded) {
      // update using my global styles object with the customization.
    }
    return countryStyles;
  };
```

and later I use that function passed as prop in my Map component:
```js
<Geography style={computedStyles(geography)} />
```

I added some logs and can't understand why the function isn't called when the data comes from the API and the parent is rerendered but it did when I clicked out.

**Comment by zimrick** [comment]
I tried to recreate your bug, but so far with no luck. The highlighting seems to work fine when using a function like this.

```js
class Map extends Component {
  static defaultProps = {
    countriesIncluded: ["SWE","ITA","AUS","BRA","THA","MEX"],
  }
  constructor() {
    super()
    this.computedStyles = this.computedStyles.bind(this)
  }
  computedStyles = geography => {
    const { countriesIncluded } = this.props
    // array of countries included
    const isCountryIncluded = countriesIncluded.includes(geography.id)

    let countryStyles = {
      default: { fill: "#EEE" },
    }

    if (isCountryIncluded) {
      // update using my global styles object with the customization.
      countryStyles = {
        default: { fill: "#FF5722" },
      }
    }

    return countryStyles
  }
  render() {
    return (
      <div>
        <div style={wrapperStyles}>
          <ComposableMap style={mapStyles}>
            <ZoomableGroup>
              <Geographies geographyUrl="/static/world-50m.json" disableOptimization>
                {(geographies, projection) =>
                  geographies.map((geography, i) =>
                    <Geography
                      key={i}
                      geography={geography}
                      projection={projection}
                      style={this.computedStyles(geography)}
                    />
                )}
              </Geographies>
            </ZoomableGroup>
          </ComposableMap>
        </div>
      </div>
    )
  }
}
```

Do you have an async request somewhere in there? The only thing I can imagine messing with this is the internal `shouldComponentUpdate` on the `Geographies` component, but you mentioned earlier that you have `disableOptimization` set to `true`, so that should not be interfering at all.

**Comment by j8seangel** [comment]
You are right, was my mistake!
I had a function to calculate the styles dynamically but the component isn't receiving the new params and that is why it wasn't being updated.
Thanks !!
