### ISSUE TITLE
ZoomableGroup with geoAlbersUsa Projection

### ISSUE THREAD

**Issue by Maintrain97** [zcreativelabs/react-simple-maps#213]
ZoomableGroup with a zoom greater than 1 throws a `TypeError: Cannot read property '0' of null`. This is easy to reproduce by adding a ZoomableGroup with zoom={2} to this example [https://www.react-simple-maps.io/examples/usa-with-state-labels/](https://www.react-simple-maps.io/examples/usa-with-state-labels/)

**Comment by zimrick** [comment]
Hi @Maintrain97,
When combining ZoomableGroup with the AlbersUSA projection you have to watch out that the center of the map stays within the "defined" area of the projection. If you just add the ZoomableGroup component with a zoom value and without a valid `center` value, you will run into problems, since the center will be at `0, 0`, which is outside the bounds of the AlbersUSA projection. To make the example work, just add a center (e.g. `[-95, 35]`).

I know this is a bit quirky, but it should only be an issue with projections that have undefined coordinates.

**Comment by Maintrain97** [comment]
Oh perfect, thank you. I had a feeling that was the issue but I hadn't been able to find a center that worked.
