### ISSUE TITLE
Cannot read property 'componentIdentifier' of undefined

### ISSUE THREAD

**Issue by pronebird** [zcreativelabs/react-simple-maps#24]
Hi,

I render an array of annotations and then output it in JSX tree as usual, but something goes wrong and I get

>./node_modules/react-simple-maps/lib/utils.js:59 Uncaught (in promise) TypeError: Cannot read property 'componentIdentifier' of undefined

```js
const countryAnnotations = countryGeometries.map((item, i) => {
  return (
    <Annotation key={ i } dx={ item.coordinates[0] } dy={ item.coordinates[1] }>
      <text fill="white">{ item.properties.name }</text>
    </Annotation>
  );
});

return (
  <Motion defaultStyle={ initialStyle } style={ motionStyle }>
    {({zoom, x, y}) => (
      <ComposableMap width={ 800 } height={ 450 } style={ mapStyle } projectionConfig={ projectionConfig }>
        <ZoomableGroup center={ [x, y] } zoom={ zoom } disablePanning={ true }>
          <Geographies geographyUrl={ geometryJSON }>
            {(geographies, projection) => geographies.map((geography, i) => (
              <Geography
                key={ `geography-${i}` }
                geography={ geography }
                projection={ projection }
                style={ geographyStyle } />
            ))}
          </Geographies>
          { countryAnnotations }
        </ZoomableGroup>
      </ComposableMap>
    )}
  </Motion>
);
```

**Comment by pronebird** [comment]
I actually think that the problem is in JSX. Would that be possible to group `Annotation`s under `<Annotations>`? I tried to add the `Annotations` element same way as `Markers` but I got some errors when doing this.

**Comment by zimrick** [comment]
Yes, the problem is that `Annotation` is currently not handled the same way as `Markers` in that it cannot handle loops. What you say makes sense, they could be looped over if I add a new `Annotations` component and then they can be treated similarly to `Markers`.

I am going to put this on my immediate todo. In the meantime I would suggest using markers instead. Note, that you can have multiple groupings of markers, so one could be dedicated to annotations. They are also very powerful since they can contain custom SVG.

**Comment by pronebird** [comment]
Thanks! Indeed, I switched to markers since I realized that in my case there is no big difference.

**Comment by zimrick** [comment]
As of v0.9.0, you can now wrap your annotations in the `<Annotations />` component and map over annotations the same way as you would with markers.
