### ISSUE TITLE
Line component: lines connecting to marker are not working properly

### ISSUE THREAD

**Issue by sumeetrane-technosoft** [zcreativelabs/react-simple-maps#293]
<img width="1440" alt="Screenshot 2022-07-22 at 12 44 10 PM" src="https://user-images.githubusercontent.com/109060862/180426650-76355993-f370-4f99-af57-d9e87306750a.png">
 The lines connecting from California to mumbai should flow in a straight line & not the other way around. How can i make it flow in a straight way ?

**Comment by zimrick** [comment]
Hi @sumeetrane-technosoft,
The line component uses a geojson lineString under the hood, so the line you are seeing is the 'shortest' route between Mumbai and California. Unfortunately with this projection, this results in a line that looks a bit strange and does not have the desired outcome.

There are a few options for a solution here. The most useful one is probably to use the `MapContext` to create a `CustomLine` component that draws a simple line between point A and point B. That way, the line will always stay within the SVG viewport.

I made a [codesandbox example](https://codesandbox.io/s/custom-line-example-416ome?file=/src/MapChart.js) for you, since the `MapContext` is not well documented at the moment. We are working on a new documentation site that should be out very shortly.
