### ISSUE TITLE
Externally triggering a Geography active state, and displaying a Marker...

### ISSUE THREAD

**Issue by kelexel** [zcreativelabs/react-simple-maps#8]
Hello !

I'm wondering, would there be a way to "trigger" the state "active" of a given Geography component based on it's ID ?

In my use case, I have a simple list of country IDs, and want a given country to "light up" on the map, and show a marker relative to it's position with some custom content..

My main issue is trying to figure how to make a given Geography component react to a state change.

I tried to do something ugly, like switching the style passed to Geography components :

```
constructor(props) {
  super(props);
  this.state = {
    zoom: 2,
    activeId: 'FRA'
  }
  this._onZoomIn = this._onZoomIn.bind(this)
  this._onZoomOut = this._onZoomOut.bind(this)
}
...
_onGeographyClick(geography) {
  console.log('clicked on', geography)
  this.setState({activeId: geography.id})
}
render() {
  const { activeId } = this.state;
  ...
  return (<div style={{height: 'calc(100% - 60px)'}} className={styles.mapWrapper}>
    <button onClick={ this._onZoomIn }>{ "Zoom in" }</button>
    <button onClick={ this._onZoomOut }>{ "Zoom out" }</button>
    <hr />
    <ComposableMap
      width={window.innerWidth - 405}
      height={window.innerHeight - 60}
      >
      <ZoomableGroup zoom={ this.state.zoom } disablePanning={true}>
        <Geographies geographyUrl={ "/static/content/maps/world-50m.json" }>
          {(geographies, projection) => geographies.map((geography, i) => {

           /* 
               Fugly Alert
           */
            const cellStyle = geography.id == activeId ? { fill: "#ff0000", stroke: "#ff0000", strokeWidth: 0.5, outline: 'none' } : { fill: "#666", stroke: "#FFF", strokeWidth: 0.5, outline: 'none' };

            return (<Geography
              key={ `geography-${i}` }
              geography={ geography }
              projection={ projection }
              onClick={this._onGeographyClick.bind(this)}
              style={{
                default: cellStyle,
                hover:   cellStyle,
                pressed: cellStyle,
              }}
            />)
          })}
        </Geographies>
      </ZoomableGroup>
    </ComposableMap>
  </div>);
}

```
While it worked for the initial state of the component, 
But the style never gets re-evaluated when I setState({activeId: '<SOME_ID>');
So I am guessing this is the wrong way of doing it..

Would you see a way to achieve this ?

Cheers

**Comment by zimrick** [comment]
Hi there,

You have the right idea of how to do this. The thing that is getting in the way is that `react-simple-maps` locks the geographies once they are rendered out the first time, in order to improve performance with panning and zooming (especially when using animation libraries). There are a couple of ways of achieving what you want.

1. Use `disableOptimization` prop

There is a `prop` for the `<Geographies />` component called `disableOptimization`, which will make sure that the geographies are rerendered every time. [Check out the docs here](https://github.com/zcreativelabs/react-simple-maps#-geographies-). You can easily disable this permanently.

2. Bypass the optimization once by using setState callback

If you plan on adding panning and zooming functionality to your map at a later stage, the safe bet would be to use a setState callback to bypass the optimization only once. It would work something like this:

```js
...
_onGeographyClick(geography) {
  console.log('clicked on', geography)
  this.setState({
    disableOptimization: true,
    activeId: geography.id,
  }, () => {
    this.setState({
      disableOptimization: false,
    })
  })
}
...
<Geographies geographyUrl={ "/static/content/maps/world-50m.json" } disableOptimization={this.state.disableOptimization}>
  {(geographies, projection) => geographies.map((geography, i) => {
  ...
```

Let me know if you run into any trouble with this.

Cheers
