### ISSUE TITLE
Trigger redrawing of Geographies? 

### ISSUE THREAD

**Issue by garygcchiu** [zcreativelabs/react-simple-maps#93]
Hey,

I want to create some behaviour where if the user selects a continent (this.state.selectedContinent changes to 'NA' or something), I want all the countries that belong to that continent to highlight. 

What I have to far is I added the continent to the world JSON data for each country using a little script. Then, in the `style` prop inside` <Geography>`, I have something like: 

```jsx
geographies.map((geography, i) => ...
    <Geography
        key={i}
        geography={geography}
         ...
        style={{
            default: this.countryInRegion(geography) ? colours.highlighted : colours.default,
            hover: colours.hover,
            pressed: colours.pressed,
        }}
    />
```

The problem is, `this.countryInRegion()` is only called when the component initially mounts. Even if I force a re-render (`this.forceUpdate()` after this.state.selectedContinent changes), the geographies don't call `this.countryInRegion()` and recalculate the styling. I've also tried moving the `geographies.map()` outside of the `return` in the render method, but still no luck. 

Is there a way to achieve my desired behaviour? Is there a way to "trigger" `geographies.map()` again?

**Comment by zimrick** [comment]
Hi @garygcchiu,

Yup, `<Geographies />` by default tries to block rerendering, for better performance especially when panning and zooming or using animation libs to pan and zoom around a map. In order to make the geographies rerender the way you want, you will have to pass the `disableOptimization` prop to the `<Geographies />` component. Check the docs here:
https://github.com/zcreativelabs/react-simple-maps#-geographies

If you will be using panning and zooming I would recommend you add the `cacheId` prop to your `<Geography />` items. You are not altering the geographies, just the color, so the caching should be very effective, and it should fix any performance issues.

Your code would look something like this:

```jsx
<Geographies geography={...} disableOptimization>
  {
    geographies.map((geography, i) => ...
      <Geography
          key={i}
          cacheId={"<Make this some unique id (e.g. iso3)...>"}
          geography={geography}
          ...
          style={{
            default: this.countryInRegion(geography) ? colours.highlighted : colours.default,
            hover: colours.hover,
            pressed: colours.pressed,
          }}
      />
  }
</Geographies>
```

Let me know if this solves the problem.

**Comment by garygcchiu** [comment]
Wew, it works perfectly! Thank you so much for the quick help!

**Comment by wezleytsai** [comment]
How do you accomplish this in v2?
